name: 'Digger run'

on:
  pull_request:
    branches:
      - develop
    types: 
      - closed
      - opened
      - synchronize
      - reopened
  issue_comment:
    types: 
      - created
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - name: Echo command for debugging
        run: |
          echo "debug echo"
          # env

      - name: digger run
        uses: diggerhq/digger@v0.2.4
        with:
          setup-aws: true
          # For OIDC:
          #     https://docs.digger.dev/cloud-providers/authenticating-with-oidc-on-aws
          #     https://github.com/aws-actions/configure-aws-credentials#OIDC
          aws-role-to-assume: ${{ secrets.LAB_AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1

          # https://github.com/diggerhq/digger/blob/develop/action.yml
          configure-checkout: true
          setup-terragrunt: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
